name: Publish Docker image
on:
  push:
    branches:
      - master
jobs:

  build:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Build and Publish
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKER_USERNAME }}/standard-ubuntu-environment:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/standard-ubuntu-environment
